### ISSUE TITLE
Shaku component without a derive Default requirement for with_component_parameters instantiation

### ISSUE THREAD

**Issue by elertan** [Mcat12/shaku#1]
I have a component that is dependent on a db connection pool field, which I am passing via the `with_component_parameters` on container creation. This works great, however the fields on the component type have to derive `Default`, presumably due to the possibility of using the component without providing parameters, and thus relying on default values.

Due to that requirement, I have to do something like this:
```rs
#[derive(Component)]
#[shaku(interface = GenderService)]
pub struct GenderServiceImpl {
    pub pool: Option<Pool<ConnectionManager<PgConnection>>>,
}
```
where I mark the field as an `Option`, so I can let it Default to `None`. But since I always have a connection pool available, I just unwrap the value in every scenario, which to me is a code smell (because it is unnecessary, I'd rather just pass in the Pool right away).
Is there a way I can get around this requirement?

**Comment by Mcat12** [comment]
First off, thanks for using shaku and opening its first issue!

There's two immediate fixes you could do, depending on how your project is set up. First, remove the `Option` wrapper, then either:

1. Add `#[shaku(default = create_db_pool())]` onto the property. This is assuming you are able to create a connection pool without any extra configuration.
2. Since you will never need to actually use the default value, you could use `#[shaku(default = unimplemented!())]`.

That's my first pass at the issue. Tomorrow I'll try them out myself to make sure they work. I'm also open to changing the API to make this easier if you have any suggestions.

**Comment by Mcat12** [comment]
Ok, after testing it turns out that the second option requires enabling the "full" feature in `syn` (in order to parse more types of expressions). This will be fixed in the next version, but for now you can make a separate function and call it like so:
```rust
fn unreachable_default<T>() -> T {
    panic!("There is no default value for {}", std::any::type_name::<T>())
    // Or just call unreachable!()
}

#[derive(Component)]
#[shaku(interface = GenderService)]
pub struct GenderServiceImpl {
    #[shaku(default = unreachable_default())]
    pub pool: Pool<ConnectionManager<PgConnection>>,
}
```

**Comment by elertan** [comment]
Hi, thanks for the quick reply. I'll try this out later, seems like a reasonable solution for the time being. Thanks!

**Comment by elertan** [comment]
This works well, thanks!
```rs
#[derive(Component)]
#[shaku(interface = GenderService)]
pub struct GenderServiceImpl {
    #[allow(unreachable_code)]
    #[shaku(default = unreachable!())]
    pub pool: Pool<ConnectionManager<PgConnection>>,
}
```

**Comment by Mcat12** [comment]
Out of curiosity, are you tracking master in order to directly use `unreachable!()`, or maintaining a fork? That wasn't working for me on 0.2.0.

I'm currently working on some new features (submodules!) and will publish 0.3.0 sometime soon.

**Comment by Mcat12** [comment]
v0.3.0 has just been released, and includes the syn "full" feature-flag fix.

**Comment by elertan** [comment]
I’m still using version 0.2.0 with `unreachable!()` on the latest stable release of rust (`1.47.0`?). Compiled without any issues for me. Also it’s nice to see how quickly this got resolved, thanks again.

**Comment by Mcat12** [comment]
Ah, it might be that one of your dependencies is already using `syn` with the `full` feature flag, which then enables it for shaku's derive macros as well.
