### ISSUE TITLE
Feature request: Qualifiers

### ISSUE THREAD

**Issue by leinardi** [Mcat12/shaku#10]
I'll quote the definition of Qualifiers form [Dagger dev guide](https://dagger.dev/dev-guide/):

> Sometimes the type alone is insufficient to identify a dependency. For example, a sophisticated coffee maker app may want separate heaters for the water and the hot plate.
> 
> In this case, we add a qualifier annotation. 
> 
> You can create your own qualifier annotations, or just use `@Named`. Apply qualifiers by annotating the field or parameter of interest. The type and qualifier annotation will both be used to identify the dependency.
> 
> ```
> class ExpensiveCoffeeMaker {
>   @Inject @Named("water") Heater waterHeater;
>   @Inject @Named("hot plate") Heater hotPlateHeater;
>   ...
> }
> ```
> Supply qualified values by annotating the corresponding `@Provides` method.
> 
> ```
> @Provides @Named("hot plate") static Heater provideHotPlateHeater() {
>   return new ElectricHeater(70);
> }
> 
> @Provides @Named("water") static Heater provideWaterHeater() {
>   return new ElectricHeater(93);
> }
> ```
> Dependencies may not have multiple qualifier annotations.

**Comment by Mcat12** [comment]
Have you seen this feature used in real life projects? I'm curious how often this is used.

**Comment by leinardi** [comment]
I can't tell how often is used but, in the company where I work, we use it to provide 2 different instances of the `StorageManager` (it persist key/value pairs inside an SQLite database): one instance is persisted until you uninstall the app, the other is wiped when the user logs out. But they are both instances of the same `StorageManager` class.

**Comment by Mcat12** [comment]
So a direct translation into Rust seems to have issues, as now resolving a component could require a runtime lookup due to the string key. I think that would impact the ability to check that component dependencies are valid, and that there _does_ exist an instance of the interface in the module. Const generics might help with this, but it's not stable. I think shaku can support the spirit of this feature by qualifying the service type with a generic.

In your example, this might look like:
```rust
trait StorageManager<Scope: Interface>: Interface {
    // ...
}

struct AppScope;
struct UserScope;

#[derive(Component)]
#[shaku(interface = StorageManager<Scope>)]
struct StorageManagerImpl<Scope: Interface> {
    // ...
    _scope: PhantomData<Scope>
}

impl<Scope: Interface> StorageManager<Scope> for StorageManagerImpl<Scope> {
    // ...
}

module! {
    MyModule {
        components = [StorageManagerImpl<AppScope>, StorageManagerImpl<UserScope>],
        providers = []
    }
}

fn main() {
    let my_mod = MyModule::builder().build();
    let app_storage: &dyn StorageManager<AppScope> = my_mod.resolve_ref();
    let user_storage: &dyn StorageManager<UserScope> = my_mod.resolve_ref();
}
```

**Comment by Mcat12** [comment]
@leinardi What do you think of the above alternative? I think this is the best reasonable implementation of qualifiers which keeps shaku's compile time guarantees, at least until const generics becomes stable. Once const generics becomes stable, I can see something like the following being possible:
```rust
trait HasComponent<Interface: ?Sized, const Name = "default"> {
    // ...
}

// Compiles if module implements HasComponent<dyn MyComponent, "default">
let component = module.resolve_ref::<dyn MyComponent, _>();

// Compiles if module implements HasComponent<dyn MyComponent, "qualifier">
let component = module.resolve_ref::<dyn MyComponent, "qualifier">();
```

**Comment by leinardi** [comment]
Hey sorry, I forgot to answer: I think is fine! It's pretty straight forward to use :+1: 
Thanks :)
