### ISSUE TITLE
Suggestion: better documentation for custom Components

### ISSUE THREAD

**Issue by leinardi** [Mcat12/shaku#11]
I think that the getting started guide should provide information about the use of a custom `Component`. Similar to what I have already suggested in #9 but, beside being available in a sample code that can be downloaded via `git`, a simplified versions should be available also on the official documentation.

**Comment by Mcat12** [comment]
Are you referring to manually implementing the `Component` trait?

**Comment by leinardi** [comment]
I'm talking about this:
```rust
impl<M: Module + HasComponent<dyn Logger>> Component<M> for DateLoggerImpl {
    type Interface = dyn DateLogger;
    type Parameters = ();

    fn build(context: &mut ModuleBuildContext<M>, parameters: ()) -> Box<dyn DateLogger> {
        Box::new(Self::new(context.build_component()))
    }
}
```
Is it already documented? I quickly looked for it but I was not able to find it.

**Comment by Mcat12** [comment]
There is some documentation available on the trait: https://docs.rs/shaku/0.5.0/shaku/trait.Component.html
And it's referenced once in the main guide: https://docs.rs/shaku/0.5.0/shaku/guide/index.html#express-dependencies

Note: the 0.5.0 docs for `Component::build` incorrectly say to use `M::resolve` to inject dependencies. The guide correctly says to use [`M::build_component`](https://docs.rs/shaku/0.5.0/shaku/trait.HasComponent.html#tymethod.build_component) (note: this is different from `context.build_component`).

You can also look at [`simple_no_macros.rs`] and [`simple_with_macros.rs`] in the examples folder to see how the derive macro and trait implementations work.

[`simple_no_macros.rs`]: https://github.com/Mcat12/shaku/blob/master/shaku/examples/simple_no_macros.rs
[`simple_with_macros.rs`]: https://github.com/Mcat12/shaku/blob/master/shaku/examples/simple_with_macros.rs
