### ISSUE TITLE
documentation : How to use shaku with a constructor

### ISSUE THREAD

**Issue by pgokul** [Mcat12/shaku#13]
I am new to Rust and and am unable to figure out how to use a constructor with shaku dependency injection.

```
trait IConfig: Interface {}
#[derive(Component)]
#[shaku(interface = IConfig)]
struct IConfigImpl {
    url: String,
}
impl IConfig for IConfigImpl {}

trait IService: Interface {
    fn register_user(&self, email: &str, pwd: &str) -> String;
}
#[derive(Component)]
#[shaku(interface = IService)]
struct IServiceImpl {
    #[shaku(inject)]
    config: Arc<dyn IConfig>,
    usr_store: RwLock<HashMap<String, String>>,
}

impl IServiceImpl {
    pub fn new() -> IServiceImpl {
        IServiceImpl {
            usr_store: RwLock::new(HashMap::new()),
        }
    }
}
```

I am getting an error,  ' missing field `config` in initializer of IServiceImpl

Adding default throws an error "the trait `std::default::Default` is not implemented for `dyn IConfig::IConfig`"

How can i use a constructor where certain fields of the struct are  initialized and certain others are injected.

**Comment by Mcat12** [comment]
The `Component` derive automatically generates a parameters struct (ex. `IServiceImplParameters`) which can be used to supply all of the non-injected properties during module creation. Here's the section of the documentation which talks about this: https://docs.rs/shaku/0.5.0/shaku/guide/index.html#passing-parameters

If the type of a property implements [`Default`](https://doc.rust-lang.org/stable/std/default/trait.Default.html), you don't need to manually pass it in to get the default value for the type. For example, your `IServiceImpl` seems to only need a default value for `RwLock<HashMap<String, String>>`, so you don't need to use `with_component_parameters` on it.

In your example, it looks like you also need to declare a module to hold your components. Your code might end up looking like this:
```rust
module! {
    MyModule {
        components = [IConfigImpl, IServiceImpl],
        providers = []
    }
}

fn main() {
    let my_mod = MyModule::builder()
        .with_component_parameters::<IConfigImpl>(IConfigImplParameters {
            url: "insert-url-here".to_string()
        })
        .build();
}
```

Note: In Rust, traits and structs are normally named without a leading "I". For example, your `IService` and `IServiceImpl` would be `Service` and `ServiceImpl`.

**Comment by pgokul** [comment]
Thanks @Mcat12 . Would this mean that the code which creates the modules needs to be aware of the internal details of the component to be created if the component has some properties which require non trivial construction. This would mean the internal details of the object would be leaking into the module creators. 
Is support planned/available for something like @PostConstruct annotation in java JSR 250.

**Comment by Mcat12** [comment]
You can also add an annotation to the property to provide a default, which would move that code closer to the implementation:
```rust
#[derive(Component)]
#[shaku(interface = IConfig)]
struct IConfigImpl {
    #[shaku(default = "insert-url-here".to_string())]
    url: String,
}
```

The `default` field in the annotation is an expression, so it can be a function call to more complex code.

Alternatively, you could write the `Component` implementation by hand to have full control over how the service gets created:
```rust
struct IServiceImpl {
    config: Arc<dyn IConfig>,
    usr_store: RwLock<HashMap<String, String>>,
}

impl<M: Module + HasComponent<dyn IConfig>> Component<M> for IServiceImpl {
    type Interface = dyn IService;
    type Parameters = ();

    fn build(context: &mut ModuleBuildContext<M>, params: Self::Parameters) -> Box<Self::Interface> {
        // Insert initialization code here
        let usr_store = RwLock::default();

        Box::new(IServiceImpl {
            config: M::build_component(context),
            usr_store
        })
    }
}
```
Note that the `Component` derive and `shaku` annotations are removed, since the impl is written manually.

**Comment by pgokul** [comment]
Writing the Component implementation by hand seems to be the cleanest way to do this. I will try this.

**Comment by Mcat12** [comment]
Thanks for the question!
