### ISSUE TITLE
Async support for Option<&mut T>

### ISSUE THREAD

**Issue by petar-dambovaliev** [Mcat12/shaku#15]
Support for this would be nice, as it would enable this feature to be used with async web applications.
Ideally, we would like to have synchronisation only in places where the same `&mut T` is being injected,
without locking up the whole container but just that `T`.

From what i see now, it seems that this is only addressed via an example that locks up the whole module.

**Comment by Mcat12** [comment]
Are you talking about [`resolve_mut`]? I'm not sure how async fits into this. Can you elaborate on this issue?

[`resolve_mut`]: https://docs.rs/shaku/0.5.0/shaku/trait.HasComponent.html#tymethod.resolve_mut

**Comment by petar-dambovaliev** [comment]
> Are you talking about [`resolve_mut`](https://docs.rs/shaku/0.5.0/shaku/trait.HasComponent.html#tymethod.resolve_mut)? I'm not sure how async fits into this. Can you elaborate on this issue?

Yes, i am talking about `resolve_mut`.
I am using `shaku` to resolve  http handler methods that are being executed by `tokio`.
`resolve_mut` requires a mutable reference to the module. Therefore, the only solution at the moment is to use a `Mutex` on the module. Is that correct or i am missing something?

**Comment by Mcat12** [comment]
I'm actually planning on removing `resolve_mut` to support lazy initialization of components (#7, there will be multiple Arc references to each component, which prevents `Arc::get_mut` from working).

Do you need a mutable reference to the component? Even with a mutable reference to the module, there can be other Arc references to the components which prevent acquiring a mutable reference to the component. Usually if you need to mutate a component, you would add the mutex inside of the component. If your web server does not require the module to be thread-safe (e.g. it builds an independent module for each thread), then you could also disable the `thread_safe` feature of shaku and use [`RefCell`].

[`RefCell`]: https://doc.rust-lang.org/stable/std/cell/struct.RefCell.html

**Comment by petar-dambovaliev** [comment]
> I'm actually planning on removing `resolve_mut` to support lazy initialization of components (#7, there will be multiple Arc references to each component, which prevents `Arc::get_mut` from working).
> 
> Do you need a mutable reference to the component? Even with a mutable reference to the module, there can be other Arc references to the components which prevent acquiring a mutable reference to the component. Usually if you need to mutate a component, you would add the mutex inside of the component. If your web server does not require the module to be thread-safe (e.g. it builds an independent module for each thread), then you could also disable the `thread_safe` feature of shaku and use [`RefCell`].
> 
> [`RefCell`]: https://doc.rust-lang.org/stable/std/cell/struct.RefCell.html

No, I don't require this. The only reason I am supporting it in my web framework is because `shaku` supports it. I was just thinking that if this feature was to be supported,  a more efficient algorithm can be implemented for this specific case than using a mutex. However, if you will remove this feature, then I don't need to worry about it.

**Comment by Mcat12** [comment]
Yeah, logically it's almost impossible to ensure that you can get a mutable reference to a component directly. If a mutable reference exists, then there can be no other references _at all_ to the data it points to. That means the component cannot be a dependency of another component, and the `Arc` reference cannot have been cloned/shared to somewhere else. `resolve_mut` only worked in a handful of cases due to this, and is hard to use.

The proper solution to getting mutable access to a component is using an internal mutex (or similar constructs like a RwLock). Luckily Rust will tell you when this is necessary :slightly_smiling_face:.

**Comment by petar-dambovaliev** [comment]
> Yeah, logically it's almost impossible to ensure that you can get a mutable reference to a component directly. If a mutable reference exists, then there can be no other references _at all_ to the data it points to. That means the component cannot be a dependency of another component, and the `Arc` reference cannot have been cloned/shared to somewhere else. `resolve_mut` only worked in a handful of cases due to this, and is hard to use.
> 
> The proper solution for getting mutable access to a component is using an internal mutex (or similar constructs like a RwLock). Luckily Rust will tell you when this is necessary 🙂.

Theoretically, you can add N `AtomicBool` to N components that require mutable access.
Then, you can return `None` by checking the atomic flag.
And this would cost the user only for the places where `&mut T` is requested.
At the end, no one would be blocked. `AtomicBool` is pretty efficient.

**Comment by Mcat12** [comment]
That's effectively the same as a mutex (`try_lock`) or `RwLock`, but you're more likely to get the implementation wrong.

**Comment by Mcat12** [comment]
Thanks for the question, and feel free to open more issues or use GitHub Discussions for future questions!
