### ISSUE TITLE
Question: performance 

### ISSUE THREAD

**Issue by petar-dambovaliev** [Mcat12/shaku#17]
is it worth adding benchmarks to prevent performance regressions in the future?
Also, if not adding new features, we can try to make the existing features faster.
I wonder if work on that has been done etc..

**Comment by Mcat12** [comment]
Thanks for thinking about performance and the future of the library! I don't think there's currently much need for performance benchmarks, but it's a question worth asking.

The library doesn't do much computation, so testing performance would mostly just be testing how fast `HashMap::get` and `Arc::as_ref` are. Compared to dependency injection in other languages like Java where runtime reflection is used, this library is extremely lean. Most of the "work" happens at compile time (proc macros expand code) and startup (creating the instances). This work is necessary (hard to optimize further algorithmically) and a one-time cost.

If you are concerned about performance, I would suggest profiling your application to determine where the performance issue is. I highly doubt dependency injection would come before optimizing the application's code, IO usage, or (if applicable) web framework.

If you do find an issue with performance, feel free to bring it up and it will get looked into. Also, if the library does in the future start doing more computation, then at that point it may be worthwhile to add benchmarks. Until then, I think don't think benchmarks would be useful.

**Comment by petar-dambovaliev** [comment]
I completely agree, it doesn't make much sense to optimise work that is being done at compile time. At least, not if it's not unbearably slow. Incremental compilation makes it a non issue. Currently, I do not have any issues. I just wanted for us to be aware of it as the framework develops.
