### ISSUE TITLE
First-paragraph readme explanation of Components and Providers

### ISSUE THREAD

**Issue by austinjones** [Mcat12/shaku#19]
When I first looked at Shaku, it seemed like it only supported Components and Arc<dyn Trait> injection.  It took a lot more reading to figure out that Provider can be used to inject owned values.  Some 'up-front' documentation on the types of supported injection would be a nice doc improvement.

By the way, this is a great library!  It brings Rust so close to feature parity with Spring Boot.

**Comment by Mcat12** [comment]
With https://github.com/Mcat12/shaku/commit/0c18487c88a3e5861ec4bf75436ec0b793b926e7 and https://github.com/Mcat12/shaku/commit/0c18487c88a3e5861ec4bf75436ec0b793b926e7 I added links to the guides, which includes a link to providers. This should raise awareness of providers. I also added a section comparing components and providers, with another link to the respective guides. Hopefully this helps.
