### ISSUE TITLE
Support for owned, clonable components

### ISSUE THREAD

**Issue by austinjones** [Mcat12/shaku#21]
It would be really useful if you could define components that would be injected as Self, and cloned instead of shared with Arc.  Many types in Rust internally maintain shared state behind an Arc, and can be cloned as cheaply as the Arc wrapper that Shaku provides.

A good example is `mongodb::Client` (more details in #20).

Here is an example with an invented client struct:
```
struct Shared { ... }

#[derive(Component, Clone)]
#[shaku(interface = Self)]
struct Connection { shared: Arc<Shared> }

module! {
    MyModule {
        components = [#[cloned] Connection],
        providers = []
    }
}
```

**Comment by Mcat12** [comment]
I feel like the workaround of just calling `module.resolve_ref().clone()` would work just fine. Why should this be special-cased? Can you give more details on your requirements; perhaps there is a better way to solve your problem (e.g. database pool).

**Comment by Mcat12** [comment]
@austinjones Can you elaborate on your issue/proposal? Otherwise the issue will be closed.
