### ISSUE TITLE
Support 'scope' definitions for Component and Provider bindings

### ISSUE THREAD

**Issue by austinjones** [Mcat12/shaku#22]
I couldn't find a way to create a Component binding for a type in another crate due to the Rust orphan rules.  It seems like Provider would be the way to construct the value, but in this case, I need a shared reference.

Components and Providers could support some kind of scope binding.  There are a few I can think of:
- #[singleton] bound to `Arc<Interface>`
- #[singleton] #[cloned] bound to `Interface` where `Interface: Clone` (see #21)
- #[transient] bound to `Self`, and constructed on each injection request

I think the current behavior is a 'good default'.  Components would use #[singleton], and Providers would use #[transient].

**Comment by Mcat12** [comment]
@austinjones Can you elaborate on your issue/proposal? Otherwise the issue will be closed.
