### ISSUE TITLE
Suggestion: Rustify example shown on the README

### ISSUE THREAD

**Issue by elertan** [Mcat12/shaku#4]
The current example really aligns with developers that work with languages such as C#, where it is convention to prefix interfaces with a capital I. However rust does not have this convention of doing things in that way.

I personally like the convention of using the Trait's name followed by Impl if it is directly and strictly used for implementing that Trait.

I do understand however that most developers that are interested in a crate like shaku probably are used to having a dependency injection library from their language of choice (like C# with ASP.NET's DI container).

What if we provide 2 examples which showcases a version that aligns more with C# developers and one which aligns more with Rust developers?

**Comment by Mcat12** [comment]
The current example is originally from the original authors' code, so I'm perfectly fine with replacing it to be more idiomatic and easier to understand. I'm fine with having just one Rust-focused example. The code should still be amicable to people with DI backgrounds in other languages, especially due to the derive macros.

**Comment by Mcat12** [comment]
I removed the `I` prefix from the traits, what do you think of it now? https://github.com/Mcat12/shaku/commit/33b338149be9d8c9c3e0fbe73a89d37bd25dccbf

**Comment by elertan** [comment]
I think this is better, but that said, it would be nice to provide an example where you directly implement a specific trait for a type where you would've usually used the same name without the I prefix.

For example:
`ILogService` and `LogService` is a common pattern.
But renaming this trait to
`LogService` might throw someone off that has a dotnet background because the naming convention is different.
Might be a good idea to provide this
`LogService` and `LogServiceImpl` as well to showcase this pattern in a more rusitfied manner?

**Comment by Mcat12** [comment]
Are you thinking of having the whole example re-done, or just renaming the types, i.e:
- `Output`/`ConsoleOutput` -> `Logger`/`LoggerImpl`
- `DateWriter`/`TodayWriter` -> `DateWriter`/`DateWriterImpl`

**Comment by Mcat12** [comment]
@elertan I've done some further rustify-ing with https://github.com/Mcat12/shaku/commit/ab728b98ae18ec0034b1e50c4b0a0de243db7ad8, what do you think?

**Comment by elertan** [comment]
Looks good 👍
